"""
Django settings for ecommerce_core project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

MEDIA_URL = '/media/'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^wqdz^19a7l&38_n9(fh=&@e%!gptlu8kjeqeuifdx-7iuh$$_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'catalog',
    'cart',
    'orders',
    'authentication',
    'rest_framework_simplejwt',
    'corsheaders',
    'payments',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # For session-based authentication
    'django.middleware.csrf.CsrfViewMiddleware',  # For CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # For session-based authentication
    'django.contrib.messages.middleware.MessageMiddleware',  # For handling messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # For clickjacking protection
    'corsheaders.middleware.CorsMiddleware',  # For handling CORS
]
CSRF_COOKIE_SECURE = False  # Use True if using HTTPS
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000']  # Add the origin of your frontend if needed  # Use True if using HTTPS
CSRF_COOKIE_HTTPONLY = True
CSRF_USE_SESSIONS = False

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    # Add other origins as needed
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'ecommerce_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
LOGOUT_REDIRECT_URL = '/login/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_SECURE = False



AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# settings.py
STRIPE_PUBLIC_KEY = 'pk_test_51PuFNlBPYnrvtdIsYKC53Y0jralauwIrW6FkCK1SeWsJa7V8QBhjfIjvMJ2pdSQhy5av4kaiwjCymMPOFq25XdhY00538WU3IP'
STRIPE_SECRET_KEY = 'sk_test_51PuFNlBPYnrvtdIsnZVCuuEVa84kHL05XbDH2X0HsGnbFWjAUOxmcnHTrOAb5qDmW20lsebnRuDGp2ygTyGmmYW500LI8eWm8G'
